name: "sample react deploy workflow"

on:
  pull_request:
    branches:
        - master
    types:
        - closed    



jobs:
    build & test:
        runs-on: ubuntu-latest
        
        steps:
            - name: "Checkout code"
              uses: actions/checkout@v4

            - name: "setup node"
              uses: actions/setup-node@v4
              with:
                node-version: 21